#server:
#  port:8090
#
#spring:
#  datasource:
#    url:jdbc:mysql://192.168.177.128:3306/wms?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2BB
#    drive-class-name:com.mysql.jdbc.Driver
#    username:root
#    password:123456